<?php

namespace Stev\BTIPay\Util;

class ActionCodes
{

    public const ACTION_CODE_SUCCESS = 0;
    public const ACTION_CODE_INACTIVE = 320;
    public const ACTION_CODE_ISSUER_UNAVAILABLE = 801;
    public const ACTION_CODE_BLOCKED_CARD = 803;
    public const ACTION_CODE_TRANSACTION_REJECTED = 805;
    public const ACTION_CODE_INVALID_CARD_EXPIRY_DATE = 861;
    public const ACTION_CODE_INVALID_CARD_CVV = 871;
    public const ACTION_CODE_INVALID_CARD = 905;
    public const ACTION_CODE_EXPIRED_CARD = 906;
    public const ACTION_CODE_INVALID_ACCOUNT = 914;
    public const ACTION_CODE_INSUFFICIENT_FUNDS = 915;
    public const ACTION_CODE_TRANSACTION_LIMIT_EXCEDED = 917;
    public const ACTION_CODE_INSTALLMENTS_NOT_ALLOWED = 998;
    public const ACTION_CODE_3DS_AUTH_DECLINED = 341016;
    public const ACTION_CODE_3DS_AUTH_STATUS_UNKNOWN = 341017;
    public const ACTION_CODE_3DS_CREQ_CANCELLED = 341018;
    public const ACTION_CODE_3DS_CREQ_FAILED = 341019;
    public const ACTION_CODE_3DS_RREQ_UNKNOWN_STATUS = 341020;

}